#!/bin/bash
# See the "README.md" file in this directory for details.

HERE="$(dirname "$(readlink -f "${0}")")"
export PATH=${HERE}/bin:$PATH
export LAHZEHPATH=${HERE}/
lahzeh --path $LAHZEHPATH "$@"
